name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      # 步骤 1: 运行 linter 并自动修复代码风格问题
      - name: Run linters and auto-fix
        run: pnpm lint --fix

      # 步骤 2: 如果有文件被修复, 自动将修改提交回您的仓库
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix linting issues"
          # 您可以指定只检查特定目录下的文件变更
          file_pattern: "src/**/*.vue src/**/*.ts"

      # 步骤 3 (可选): 再次检查, 确保所有问题都已修复
      - name: Verify linting
        run: pnpm lint

      - name: Run unit test
        run: pnpm test

      - name: Type check
        run: pnpm typecheck

      - name: Build the app
        run: pnpm build
